name = "table1837-tavernops"
main = "src/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./frontend/dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }